### ISSUE TITLE
To-do list for summer project

### ISSUE THREAD

**Issue by Yolandeezy** [SkyTruth/MTR#17]
- [x] ~~Get 2005 NAIP, where available~~ Get Landsat composites (use NAIP only where needed)
- [x] Select study area where there's good NAIP and Campagna classifications available -------- Jul 13
- [x] Have QGIS pick random points in study area
- [x] Overlay study points on imagery and define MTR vs non-MTR ------------------------------------ Jul 15
- [x] Measure accuracy of raw NDVI threshold classifications at study points
- [ ] Measure accuracy of raw NDVI threshold classifications at study points across whole study area
- [ ] ~~Measure accuracy of raw spectral classification at study points~~ ----------------------------------- Jul 22
- [ ] Run Open/Close on NDVI threshold classification 
- [ ] Run Open/Close on spectral classification -------------------------------------------------------------- Jul 29
- [ ] Measure accuracy of NDVI threshold opened/closed classification at study points
- [ ] Measure accuracy of spectral opened/closed classification at study points -------------------- Aug 4

*****

- [x] Tentative: build my own composite because the one in EE api is a TOA
- [x] Run EE script on my own composite
- [ ] Measure accuracy of classification based on my build composite at study points
- [ ] (OPTIONAL) Implement own classifier in EE (e.g. random forest)
- [ ] Produce methodology for updating MTR datasets (as automatically and consistently as possible) - Aug 21st
